alias doppler.run="doppler run"
alias doppler.run.dev="doppler run -c=dev"
alias doppler.run.prod="doppler run -c=prod"
alias doppler.run.stg="doppler run -c=stg"
alias doppler.run.test="doppler run -c=test"
